apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reforge
  title: Reforge
  description: Rust-native automated dependency updater for Helm charts and Dockerfiles on self-managed GitLab
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: procore/reforge
    github.com/team-slug: procore/team-government-engineering
    opsgenie.com/team: "[T] government engineering"
  tags:
    - rust
    - dependencies
    - helm
    - docker
    - gitlab
    - internal
  links:
    - url: https://procoretech.atlassian.net/browse/GOVENG
      title: Jira
      icon: developerBoard
    - url: https://procore.enterprise.slack.com/archives/C0994811SG4
      title: Team Slack
      icon: chat
spec:
  type: tool
  lifecycle: experimental
  owner: team-government-engineering
